include ../Makefile

# CC := gcc
# CFLAGS := -Wall -W -O -std=c99
# OBJDIR := bin

# # this is probably a really roundabout way of doing this. 
# sources := $(wildcard *.c)
# basenames := $(basename $(sources))
# obj_names := $(addsuffix .o, $(basenames))
# OBJS := $(addprefix $(OBJDIR)/, $(obj_names))

# $(OBJDIR)/%.o : %.c
# 	$(CC) $(CFLAGS) $< -o $@

# all: $(OBJS)

# $(OBJS): | $(OBJDIR)

# $(OBJDIR):
# 	mkdir $(OBJDIR)

# clean:
# 	rm $(OBJDIR)/*
